# Generated by Django 5.1.2 on 2024-10-18 10:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='handbookentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='handbooksection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='handbookentry',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='handbookentry',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
